test_dataset:
  noisy_dir: Datasets/noisy_testset_wav
  clean_dir: Datasets/clean_testset_wav
  scp: Datasets/test.scp

network:
  exp_path: D:/LNN_SE/exp_lnn_2026-05-11-15h26m
  config: configs/cfg_model.yaml
  ckpt_name: best_model_120
  checkpoint: pretrained/best_model_120.tar
  enh_folder: outputs/${network.ckpt_name}
